# Generated by Django 5.2 on 2025-08-24 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Flights",
            new_name="Flight",
        ),
    ]
